### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by cgcb** [howsecureismypassword/jquery#1]
The script will mark a too-short password as OK via CSS in the following circumstance:

1. Create a long password, triggering the .hsimp-level--good style to be applied.
2. Delete the characters (or replace them) with a password that is much shorter. Try "jeff".

You'll notice that the field is still visually indicating the password is OK. This is because the .hsimp-level--[status] styles are not removed at each level change.

**Comment by smallhadroncollider** [comment]
Good spot. I'll try and get this sorted some time this week.
